<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <AssemblyName>InfoZen</AssemblyName>
    <RootNamespace>InfoZen</RootNamespace>
    <ApplicationIcon>Assets\Icons\icon.ico</ApplicationIcon>
    <ApplicationManifest>app.manifest</ApplicationManifest>
    <Version>2.1.0</Version>
    <FileVersion>2.1.0.0</FileVersion>
    <AssemblyVersion>2.1.0.0</AssemblyVersion>
    <Authors>Octave</Authors>
    <Company>InfoZen</Company>
    <Product>InfoZen Optimiseur PC</Product>
    <Description>Optimiseur PC Windows – par Octave</Description>
    <Copyright>Copyright © 2026 Octave</Copyright>
    <PlatformTarget>AnyCPU</PlatformTarget>
    <Prefer32Bit>false</Prefer32Bit>
    <Optimize>true</Optimize>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="System.Management" Version="10.0.5" />
  </ItemGroup>

  <!-- Icône incluse dans le build -->
  <ItemGroup>
    <Resource Include="Assets\Icons\icon.ico"/>
  </ItemGroup>

</Project>
