//------------------------------------------------------------------------------
// <auto-generated>
//     Klyr v2.2.0 — Localized strings (Designer-style, hand-maintained).
//     FR is the neutral culture (Strings.resx); EN is the satellite (Strings.en.resx).
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Klyr.Resources
{
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Strongly-typed resource accessors for Klyr localizable strings.
    /// </summary>
    public static class Strings
    {
        private static ResourceManager? _resourceMan;
        private static CultureInfo? _resourceCulture;

        /// <summary>
        /// ResourceManager singleton, lazy-initialized.
        /// </summary>
        public static ResourceManager ResourceManager =>
            _resourceMan ??= new ResourceManager("Klyr.Resources.Strings", typeof(Strings).Assembly);

        /// <summary>
        /// Override la culture utilisée par toutes les lookups (par défaut = CurrentUICulture).
        /// </summary>
        public static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        private static string Get(string key) =>
            ResourceManager.GetString(key, _resourceCulture) ?? key;

        /// <summary>Format avec arguments façon string.Format, en utilisant la culture courante.</summary>
        public static string Format(string key, params object[] args) =>
            string.Format(_resourceCulture ?? CultureInfo.CurrentCulture, Get(key), args);

        // ─────────── PAGE TITLES ───────────
        public static string PageTitle_Dashboard => Get(nameof(PageTitle_Dashboard));
        public static string PageTitle_Gaming    => Get(nameof(PageTitle_Gaming));
        public static string PageTitle_OldPC     => Get(nameof(PageTitle_OldPC));
        public static string PageTitle_Cleaning  => Get(nameof(PageTitle_Cleaning));
        public static string PageTitle_Network   => Get(nameof(PageTitle_Network));
        public static string PageTitle_Streaming => Get(nameof(PageTitle_Streaming));
        public static string PageTitle_Terminal  => Get(nameof(PageTitle_Terminal));
        public static string PageTitle_Legal     => Get(nameof(PageTitle_Legal));

        // ─────────── NAV ───────────
        public static string Nav_Modules            => Get(nameof(Nav_Modules));
        public static string Nav_Tools              => Get(nameof(Nav_Tools));
        public static string Nav_OptimizationsCount => Get(nameof(Nav_OptimizationsCount));
        public static string Nav_NavigateGaming     => Get(nameof(Nav_NavigateGaming));
        public static string Nav_NavigateOldPC      => Get(nameof(Nav_NavigateOldPC));
        public static string Nav_NavigateCleaning   => Get(nameof(Nav_NavigateCleaning));
        public static string Nav_NavigateNetwork    => Get(nameof(Nav_NavigateNetwork));
        public static string Nav_NavigateStreaming  => Get(nameof(Nav_NavigateStreaming));
        public static string Nav_NavigateTerminal   => Get(nameof(Nav_NavigateTerminal));

        // ─────────── BUTTONS ───────────
        public static string Button_Run                => Get(nameof(Button_Run));
        public static string Button_RunAll             => Get(nameof(Button_RunAll));
        public static string Button_Stop               => Get(nameof(Button_Stop));
        public static string Button_Cancel             => Get(nameof(Button_Cancel));
        public static string Button_Save               => Get(nameof(Button_Save));
        public static string Button_Close              => Get(nameof(Button_Close));
        public static string Button_Yes                => Get(nameof(Button_Yes));
        public static string Button_No                 => Get(nameof(Button_No));
        public static string Button_OK                 => Get(nameof(Button_OK));
        public static string Button_Settings           => Get(nameof(Button_Settings));
        public static string Button_About              => Get(nameof(Button_About));
        public static string Button_CreateRestorePoint => Get(nameof(Button_CreateRestorePoint));
        public static string Button_ExportLogs         => Get(nameof(Button_ExportLogs));
        public static string Button_ClearLogs          => Get(nameof(Button_ClearLogs));
        public static string Button_Cancel_OptTooltip  => Get(nameof(Button_Cancel_OptTooltip));

        // ─────────── STATUS ───────────
        public static string Status_Ready      => Get(nameof(Status_Ready));
        public static string Status_Running    => Get(nameof(Status_Running));
        public static string Status_Done       => Get(nameof(Status_Done));
        public static string Status_Error      => Get(nameof(Status_Error));
        public static string Status_Cancelled  => Get(nameof(Status_Cancelled));
        public static string Status_Cancelling => Get(nameof(Status_Cancelling));
        public static string Status_Simulated  => Get(nameof(Status_Simulated));

        // ─────────── SPLASH ───────────
        public static string Splash_CheckAdmin    => Get(nameof(Splash_CheckAdmin));
        public static string Splash_LoadModules   => Get(nameof(Splash_LoadModules));
        public static string Splash_LoadSettings  => Get(nameof(Splash_LoadSettings));
        public static string Splash_AnalyzeSystem => Get(nameof(Splash_AnalyzeSystem));
        public static string Splash_Ready         => Get(nameof(Splash_Ready));

        // ─────────── DIALOGS ───────────
        public static string Dialog_Confirm_Title         => Get(nameof(Dialog_Confirm_Title));
        public static string Dialog_RunOpt_Message        => Get(nameof(Dialog_RunOpt_Message));
        public static string Dialog_RunAll_Title          => Get(nameof(Dialog_RunAll_Title));
        public static string Dialog_RunAll_Message        => Get(nameof(Dialog_RunAll_Message));
        public static string Dialog_Critical_Title        => Get(nameof(Dialog_Critical_Title));
        public static string Dialog_Critical_Message      => Get(nameof(Dialog_Critical_Message));
        public static string Dialog_AdminRequired_Title   => Get(nameof(Dialog_AdminRequired_Title));
        public static string Dialog_AdminRequired_Message => Get(nameof(Dialog_AdminRequired_Message));
        public static string Dialog_Reboot_Title          => Get(nameof(Dialog_Reboot_Title));
        public static string Dialog_Reboot_Message        => Get(nameof(Dialog_Reboot_Message));
        public static string Dialog_Quarantine_Title      => Get(nameof(Dialog_Quarantine_Title));
        public static string Dialog_Quarantine_Message    => Get(nameof(Dialog_Quarantine_Message));

        // ─────────── SETTINGS ───────────
        public static string Settings_Title               => Get(nameof(Settings_Title));
        public static string Settings_ConfirmBeforeRun    => Get(nameof(Settings_ConfirmBeforeRun));
        public static string Settings_AutoRestorePoint    => Get(nameof(Settings_AutoRestorePoint));
        public static string Settings_RebootWarning       => Get(nameof(Settings_RebootWarning));
        public static string Settings_Simulation          => Get(nameof(Settings_Simulation));
        public static string Settings_ShowAdvanced        => Get(nameof(Settings_ShowAdvanced));
        public static string Settings_Benchmarks          => Get(nameof(Settings_Benchmarks));
        public static string Settings_AutoScrollTerminal  => Get(nameof(Settings_AutoScrollTerminal));
        public static string Settings_ShowAdminBadge      => Get(nameof(Settings_ShowAdminBadge));
        public static string Settings_LightTheme          => Get(nameof(Settings_LightTheme));
        public static string Settings_Language            => Get(nameof(Settings_Language));
        public static string Settings_Language_Auto       => Get(nameof(Settings_Language_Auto));
        public static string Settings_Language_FR         => Get(nameof(Settings_Language_FR));
        public static string Settings_Language_EN         => Get(nameof(Settings_Language_EN));
        public static string Settings_LanguageRestartHint => Get(nameof(Settings_LanguageRestartHint));

        // ─────────── DASHBOARD ───────────
        public static string Dashboard_System       => Get(nameof(Dashboard_System));
        public static string Dashboard_CPU          => Get(nameof(Dashboard_CPU));
        public static string Dashboard_RAM          => Get(nameof(Dashboard_RAM));
        public static string Dashboard_Disk         => Get(nameof(Dashboard_Disk));
        public static string Dashboard_Uptime       => Get(nameof(Dashboard_Uptime));
        public static string Dashboard_OS           => Get(nameof(Dashboard_OS));
        public static string Dashboard_QuickActions => Get(nameof(Dashboard_QuickActions));

        // ─────────── COMMON MESSAGES ───────────
        public static string Msg_NoActiveAction  => Get(nameof(Msg_NoActiveAction));
        public static string Msg_TimeoutSeconds  => Get(nameof(Msg_TimeoutSeconds));
        public static string Msg_CancelledByUser => Get(nameof(Msg_CancelledByUser));
        public static string Msg_UacRefused      => Get(nameof(Msg_UacRefused));

        // ─────────── BADGES ───────────
        public static string Badge_Admin    => Get(nameof(Badge_Admin));
        public static string Badge_Reboot   => Get(nameof(Badge_Reboot));
        public static string Badge_Advanced => Get(nameof(Badge_Advanced));

        // ─────────── DASHBOARD ───────────
        public static string Dashboard_NavTitle       => Get(nameof(Dashboard_NavTitle));
        public static string Dashboard_CardCPU        => Get(nameof(Dashboard_CardCPU));
        public static string Dashboard_CardRAM        => Get(nameof(Dashboard_CardRAM));
        public static string Dashboard_CardDisk       => Get(nameof(Dashboard_CardDisk));
        public static string Dashboard_CardSession    => Get(nameof(Dashboard_CardSession));
        public static string Dashboard_CardSystem     => Get(nameof(Dashboard_CardSystem));
        public static string Dashboard_RecentActivity => Get(nameof(Dashboard_RecentActivity));
        public static string Dashboard_UptimePrefix   => Get(nameof(Dashboard_UptimePrefix));

        // ─────────── NAV BUTTONS (sidebar bottom) ───────────
        public static string Nav_Settings      => Get(nameof(Nav_Settings));
        public static string Nav_Legal         => Get(nameof(Nav_Legal));
        public static string Nav_About         => Get(nameof(Nav_About));
        public static string Nav_RestorePoint  => Get(nameof(Nav_RestorePoint));
        public static string Nav_ExportLogs    => Get(nameof(Nav_ExportLogs));

        // ─────────── TERMINAL ───────────
        public static string Terminal_Live      => Get(nameof(Terminal_Live));
        public static string Terminal_Clear     => Get(nameof(Terminal_Clear));
        public static string Terminal_ExportTxt => Get(nameof(Terminal_ExportTxt));

        // ─────────── SETTINGS DESCRIPTIONS ───────────
        public static string Settings_ConfirmDesc       => Get(nameof(Settings_ConfirmDesc));
        public static string Settings_AutoRestoreDesc   => Get(nameof(Settings_AutoRestoreDesc));
        public static string Settings_RebootDesc        => Get(nameof(Settings_RebootDesc));
        public static string Settings_SimulationDesc    => Get(nameof(Settings_SimulationDesc));
        public static string Settings_AdvancedDesc      => Get(nameof(Settings_AdvancedDesc));
        public static string Settings_BenchmarksDesc    => Get(nameof(Settings_BenchmarksDesc));
        public static string Settings_AutoScrollDesc    => Get(nameof(Settings_AutoScrollDesc));
        public static string Settings_AdminBadgeDesc    => Get(nameof(Settings_AdminBadgeDesc));
        public static string Settings_LightThemeDesc    => Get(nameof(Settings_LightThemeDesc));
        public static string Settings_HeaderSecurity    => Get(nameof(Settings_HeaderSecurity));
        public static string Settings_HeaderInterface   => Get(nameof(Settings_HeaderInterface));
        public static string Settings_HeaderLanguage    => Get(nameof(Settings_HeaderLanguage));

        // ─────────── OPTIM NAMES ───────────
        public static string Optim_gaming_highperf_Name        => Get(nameof(Optim_gaming_highperf_Name));
        public static string Optim_gaming_gamedvr_Name         => Get(nameof(Optim_gaming_gamedvr_Name));
        public static string Optim_gaming_fullscreen_Name      => Get(nameof(Optim_gaming_fullscreen_Name));
        public static string Optim_gaming_priority_Name        => Get(nameof(Optim_gaming_priority_Name));
        public static string Optim_gaming_network_latency_Name => Get(nameof(Optim_gaming_network_latency_Name));
        public static string Optim_gaming_directx_Name         => Get(nameof(Optim_gaming_directx_Name));
        public static string Optim_gaming_kill_processes_Name  => Get(nameof(Optim_gaming_kill_processes_Name));
        public static string Optim_gaming_fps_unlock_Name      => Get(nameof(Optim_gaming_fps_unlock_Name));
        public static string Optim_gaming_gpu_schedule_Name    => Get(nameof(Optim_gaming_gpu_schedule_Name));

        public static string Optim_oldpc_startup_Name    => Get(nameof(Optim_oldpc_startup_Name));
        public static string Optim_oldpc_animations_Name => Get(nameof(Optim_oldpc_animations_Name));
        public static string Optim_oldpc_registry_Name   => Get(nameof(Optim_oldpc_registry_Name));
        public static string Optim_oldpc_ram_Name        => Get(nameof(Optim_oldpc_ram_Name));
        public static string Optim_oldpc_temp_Name       => Get(nameof(Optim_oldpc_temp_Name));
        public static string Optim_oldpc_defrag_Name     => Get(nameof(Optim_oldpc_defrag_Name));
        public static string Optim_oldpc_theme_Name      => Get(nameof(Optim_oldpc_theme_Name));
        public static string Optim_oldpc_telemetry_Name  => Get(nameof(Optim_oldpc_telemetry_Name));

        public static string Optim_clean_disk_Name      => Get(nameof(Optim_clean_disk_Name));
        public static string Optim_clean_recycle_Name   => Get(nameof(Optim_clean_recycle_Name));
        public static string Optim_clean_logs_Name      => Get(nameof(Optim_clean_logs_Name));
        public static string Optim_clean_prefetch_Name  => Get(nameof(Optim_clean_prefetch_Name));
        public static string Optim_clean_bloatware_Name => Get(nameof(Optim_clean_bloatware_Name));
        public static string Optim_clean_repair_Name    => Get(nameof(Optim_clean_repair_Name));
        public static string Optim_clean_dns_cache_Name => Get(nameof(Optim_clean_dns_cache_Name));
        public static string Optim_clean_antivirus_Name => Get(nameof(Optim_clean_antivirus_Name));

        public static string Optim_net_tcpip_Name          => Get(nameof(Optim_net_tcpip_Name));
        public static string Optim_net_reset_Name          => Get(nameof(Optim_net_reset_Name));
        public static string Optim_net_dns_fast_Name       => Get(nameof(Optim_net_dns_fast_Name));
        public static string Optim_net_ping_Name           => Get(nameof(Optim_net_ping_Name));
        public static string Optim_net_telemetry_block_Name => Get(nameof(Optim_net_telemetry_block_Name));
        public static string Optim_net_flush_dns_Name      => Get(nameof(Optim_net_flush_dns_Name));
        public static string Optim_net_reset_firewall_Name => Get(nameof(Optim_net_reset_firewall_Name));
        public static string Optim_net_speed_test_Name     => Get(nameof(Optim_net_speed_test_Name));
        public static string Optim_net_info_Name           => Get(nameof(Optim_net_info_Name));

        public static string Optim_stream_perf_mode_Name     => Get(nameof(Optim_stream_perf_mode_Name));
        public static string Optim_stream_cpu_prio_Name      => Get(nameof(Optim_stream_cpu_prio_Name));
        public static string Optim_stream_game_mode_off_Name => Get(nameof(Optim_stream_game_mode_off_Name));
        public static string Optim_stream_hags_off_Name      => Get(nameof(Optim_stream_hags_off_Name));
        public static string Optim_stream_killer_Name        => Get(nameof(Optim_stream_killer_Name));
        public static string Optim_stream_clean_cache_Name   => Get(nameof(Optim_stream_clean_cache_Name));

        // ─────────── OPTIM DESCRIPTIONS ───────────
        public static string Optim_gaming_highperf_Desc        => Get(nameof(Optim_gaming_highperf_Desc));
        public static string Optim_gaming_gamedvr_Desc         => Get(nameof(Optim_gaming_gamedvr_Desc));
        public static string Optim_gaming_fullscreen_Desc      => Get(nameof(Optim_gaming_fullscreen_Desc));
        public static string Optim_gaming_priority_Desc        => Get(nameof(Optim_gaming_priority_Desc));
        public static string Optim_gaming_network_latency_Desc => Get(nameof(Optim_gaming_network_latency_Desc));
        public static string Optim_gaming_directx_Desc         => Get(nameof(Optim_gaming_directx_Desc));
        public static string Optim_gaming_kill_processes_Desc  => Get(nameof(Optim_gaming_kill_processes_Desc));
        public static string Optim_gaming_fps_unlock_Desc      => Get(nameof(Optim_gaming_fps_unlock_Desc));
        public static string Optim_gaming_gpu_schedule_Desc    => Get(nameof(Optim_gaming_gpu_schedule_Desc));

        public static string Optim_oldpc_startup_Desc    => Get(nameof(Optim_oldpc_startup_Desc));
        public static string Optim_oldpc_animations_Desc => Get(nameof(Optim_oldpc_animations_Desc));
        public static string Optim_oldpc_registry_Desc   => Get(nameof(Optim_oldpc_registry_Desc));
        public static string Optim_oldpc_ram_Desc        => Get(nameof(Optim_oldpc_ram_Desc));
        public static string Optim_oldpc_temp_Desc       => Get(nameof(Optim_oldpc_temp_Desc));
        public static string Optim_oldpc_defrag_Desc     => Get(nameof(Optim_oldpc_defrag_Desc));
        public static string Optim_oldpc_theme_Desc      => Get(nameof(Optim_oldpc_theme_Desc));
        public static string Optim_oldpc_telemetry_Desc  => Get(nameof(Optim_oldpc_telemetry_Desc));

        public static string Optim_clean_disk_Desc      => Get(nameof(Optim_clean_disk_Desc));
        public static string Optim_clean_recycle_Desc   => Get(nameof(Optim_clean_recycle_Desc));
        public static string Optim_clean_logs_Desc      => Get(nameof(Optim_clean_logs_Desc));
        public static string Optim_clean_prefetch_Desc  => Get(nameof(Optim_clean_prefetch_Desc));
        public static string Optim_clean_bloatware_Desc => Get(nameof(Optim_clean_bloatware_Desc));
        public static string Optim_clean_repair_Desc    => Get(nameof(Optim_clean_repair_Desc));
        public static string Optim_clean_dns_cache_Desc => Get(nameof(Optim_clean_dns_cache_Desc));
        public static string Optim_clean_antivirus_Desc => Get(nameof(Optim_clean_antivirus_Desc));

        public static string Optim_net_tcpip_Desc           => Get(nameof(Optim_net_tcpip_Desc));
        public static string Optim_net_reset_Desc           => Get(nameof(Optim_net_reset_Desc));
        public static string Optim_net_dns_fast_Desc        => Get(nameof(Optim_net_dns_fast_Desc));
        public static string Optim_net_ping_Desc            => Get(nameof(Optim_net_ping_Desc));
        public static string Optim_net_telemetry_block_Desc => Get(nameof(Optim_net_telemetry_block_Desc));
        public static string Optim_net_flush_dns_Desc       => Get(nameof(Optim_net_flush_dns_Desc));
        public static string Optim_net_reset_firewall_Desc  => Get(nameof(Optim_net_reset_firewall_Desc));
        public static string Optim_net_speed_test_Desc      => Get(nameof(Optim_net_speed_test_Desc));
        public static string Optim_net_info_Desc            => Get(nameof(Optim_net_info_Desc));

        public static string Optim_stream_perf_mode_Desc     => Get(nameof(Optim_stream_perf_mode_Desc));
        public static string Optim_stream_cpu_prio_Desc      => Get(nameof(Optim_stream_cpu_prio_Desc));
        public static string Optim_stream_game_mode_off_Desc => Get(nameof(Optim_stream_game_mode_off_Desc));
        public static string Optim_stream_hags_off_Desc      => Get(nameof(Optim_stream_hags_off_Desc));
        public static string Optim_stream_killer_Desc        => Get(nameof(Optim_stream_killer_Desc));
        public static string Optim_stream_clean_cache_Desc   => Get(nameof(Optim_stream_clean_cache_Desc));

        // ─────────── RESULT MESSAGES ───────────
        public static string Result_HighPerfActive       => Get(nameof(Result_HighPerfActive));
        public static string Result_LatencyOptimized     => Get(nameof(Result_LatencyOptimized));
        public static string Result_FpsUnlocked          => Get(nameof(Result_FpsUnlocked));
        public static string Result_NoTargetProcesses    => Get(nameof(Result_NoTargetProcesses));
        public static string Result_KillCancelled        => Get(nameof(Result_KillCancelled));
        public static string Result_KillDialogTitle      => Get(nameof(Result_KillDialogTitle));
        public static string Result_KillDialogMessage    => Get(nameof(Result_KillDialogMessage));
        public static string Result_ProcessesKilled      => Get(nameof(Result_ProcessesKilled));
        public static string Result_ProcessesNotKilled   => Get(nameof(Result_ProcessesNotKilled));
        public static string Result_NoProcessKilled      => Get(nameof(Result_NoProcessKilled));
        public static string Result_QuarantineRefused    => Get(nameof(Result_QuarantineRefused));
        public static string Result_QuarantineSuccess    => Get(nameof(Result_QuarantineSuccess));
        public static string Result_QuarantinePartial    => Get(nameof(Result_QuarantinePartial));
        public static string Result_QuarantineTimeout    => Get(nameof(Result_QuarantineTimeout));
        public static string Result_QuarantineLaunched   => Get(nameof(Result_QuarantineLaunched));
        public static string Result_ScanNoThreats        => Get(nameof(Result_ScanNoThreats));
        public static string Result_DefenderUnavailable  => Get(nameof(Result_DefenderUnavailable));
        public static string Result_ScanTimeout          => Get(nameof(Result_ScanTimeout));
        public static string Result_ScanCancelled        => Get(nameof(Result_ScanCancelled));
        public static string Result_ScanError            => Get(nameof(Result_ScanError));
        public static string Result_StreamerModeOn       => Get(nameof(Result_StreamerModeOn));
        public static string Result_NoEncoderDetected    => Get(nameof(Result_NoEncoderDetected));
        public static string Result_EncoderBoosted       => Get(nameof(Result_EncoderBoosted));
        public static string Result_GameModeOff          => Get(nameof(Result_GameModeOff));
        public static string Result_HagsOff              => Get(nameof(Result_HagsOff));
        public static string Result_NoParasites          => Get(nameof(Result_NoParasites));
        public static string Result_ParasitesKilled      => Get(nameof(Result_ParasitesKilled));
        public static string Result_NoObsCache           => Get(nameof(Result_NoObsCache));
        public static string Result_ObsCacheCleared      => Get(nameof(Result_ObsCacheCleared));
        public static string Result_TcpOptimized         => Get(nameof(Result_TcpOptimized));
        public static string Result_PingOptimized        => Get(nameof(Result_PingOptimized));
        public static string Result_TelemetryBlocked     => Get(nameof(Result_TelemetryBlocked));
        public static string Result_NetReset             => Get(nameof(Result_NetReset));
        public static string Result_FirewallReset        => Get(nameof(Result_FirewallReset));
        public static string Result_NoActiveAdapter      => Get(nameof(Result_NoActiveAdapter));

        // ─────────── ABOUT ───────────
        public static string About_Title             => Get(nameof(About_Title));
        public static string About_Subtitle          => Get(nameof(About_Subtitle));
        public static string About_Version           => Get(nameof(About_Version));
        public static string About_Developer         => Get(nameof(About_Developer));
        public static string About_Compatibility     => Get(nameof(About_Compatibility));
        public static string About_Framework         => Get(nameof(About_Framework));
        public static string About_DiagnosticHeader  => Get(nameof(About_DiagnosticHeader));
        public static string About_CopySystemInfo    => Get(nameof(About_CopySystemInfo));
        public static string About_ExportReport      => Get(nameof(About_ExportReport));

        // ─────────── LEGAL ───────────
        public static string Legal_Title              => Get(nameof(Legal_Title));
        public static string Legal_PrivacyHeader      => Get(nameof(Legal_PrivacyHeader));
        public static string Legal_PrivacyContent     => Get(nameof(Legal_PrivacyContent));
        public static string Legal_RestoreHeader      => Get(nameof(Legal_RestoreHeader));
        public static string Legal_RestoreContent     => Get(nameof(Legal_RestoreContent));
        public static string Legal_DisclaimerHeader   => Get(nameof(Legal_DisclaimerHeader));
        public static string Legal_DisclaimerContent  => Get(nameof(Legal_DisclaimerContent));
        public static string Legal_AuditHeader        => Get(nameof(Legal_AuditHeader));
        public static string Legal_AuditContent       => Get(nameof(Legal_AuditContent));
        public static string Legal_Footer             => Get(nameof(Legal_Footer));

        // ─────────── LOG MESSAGES ───────────
        public static string Log_AppStarted     => Get(nameof(Log_AppStarted));
        public static string Log_PrivacyNotice  => Get(nameof(Log_PrivacyNotice));
        public static string Log_AdminWarning   => Get(nameof(Log_AdminWarning));
        public static string Log_AdminConfirmed => Get(nameof(Log_AdminConfirmed));

        // ─────────── LOG CATEGORIES ───────────
        public static string Category_System    => Get(nameof(Category_System));
        public static string Category_Privacy   => Get(nameof(Category_Privacy));
        public static string Category_App       => Get(nameof(Category_App));
        public static string Category_Cleaning  => Get(nameof(Category_Cleaning));
        public static string Category_Network   => Get(nameof(Category_Network));
        public static string Category_Gaming    => Get(nameof(Category_Gaming));
        public static string Category_OldPC     => Get(nameof(Category_OldPC));
        public static string Category_Streaming => Get(nameof(Category_Streaming));
        public static string Category_Benchmark => Get(nameof(Category_Benchmark));
        public static string Category_Settings  => Get(nameof(Category_Settings));

        // ─────────── DASHBOARD INLINE ───────────
        public static string Dashboard_OptimizationsRunSuffix => Get(nameof(Dashboard_OptimizationsRunSuffix));
        public static string Dashboard_DiskUnitGo             => Get(nameof(Dashboard_DiskUnitGo));

        // ─────────── WINDOW CONTROLS TOOLTIPS ───────────
        public static string Tooltip_Minimize => Get(nameof(Tooltip_Minimize));
        public static string Tooltip_Maximize => Get(nameof(Tooltip_Maximize));
        public static string Tooltip_Close    => Get(nameof(Tooltip_Close));
    }
}
