//------------------------------------------------------------------------------
// <auto-generated>
//     Klyr v2.2.0 — Localized strings (Designer-style, hand-maintained).
//     FR is the neutral culture (Strings.resx); EN is the satellite (Strings.en.resx).
// </auto-generated>
//------------------------------------------------------------------------------

#nullable enable

namespace Klyr.Resources
{
    using System.Globalization;
    using System.Resources;

    /// <summary>
    /// Strongly-typed resource accessors for Klyr localizable strings.
    /// </summary>
    public static class Strings
    {
        private static ResourceManager? _resourceMan;
        private static CultureInfo? _resourceCulture;

        /// <summary>
        /// ResourceManager singleton, lazy-initialized.
        /// </summary>
        public static ResourceManager ResourceManager =>
            _resourceMan ??= new ResourceManager("Klyr.Resources.Strings", typeof(Strings).Assembly);

        /// <summary>
        /// Override la culture utilisée par toutes les lookups (par défaut = CurrentUICulture).
        /// </summary>
        public static CultureInfo? Culture
        {
            get => _resourceCulture;
            set => _resourceCulture = value;
        }

        private static string Get(string key) =>
            ResourceManager.GetString(key, _resourceCulture) ?? key;

        /// <summary>Format avec arguments façon string.Format, en utilisant la culture courante.</summary>
        public static string Format(string key, params object[] args) =>
            string.Format(_resourceCulture ?? CultureInfo.CurrentCulture, Get(key), args);

        // ─────────── PAGE TITLES ───────────
        public static string PageTitle_Dashboard => Get(nameof(PageTitle_Dashboard));
        public static string PageTitle_Gaming    => Get(nameof(PageTitle_Gaming));
        public static string PageTitle_OldPC     => Get(nameof(PageTitle_OldPC));
        public static string PageTitle_Cleaning  => Get(nameof(PageTitle_Cleaning));
        public static string PageTitle_Network   => Get(nameof(PageTitle_Network));
        public static string PageTitle_Streaming => Get(nameof(PageTitle_Streaming));
        public static string PageTitle_Privacy   => Get(nameof(PageTitle_Privacy));
        public static string PageTitle_Terminal  => Get(nameof(PageTitle_Terminal));
        public static string PageTitle_Legal     => Get(nameof(PageTitle_Legal));

        // ─────────── NAV ───────────
        public static string Nav_Modules            => Get(nameof(Nav_Modules));
        public static string Nav_Tools              => Get(nameof(Nav_Tools));
        public static string Nav_OptimizationsCount => Get(nameof(Nav_OptimizationsCount));
        public static string Nav_NavigateGaming     => Get(nameof(Nav_NavigateGaming));
        public static string Nav_NavigateOldPC      => Get(nameof(Nav_NavigateOldPC));
        public static string Nav_NavigateCleaning   => Get(nameof(Nav_NavigateCleaning));
        public static string Nav_NavigateNetwork    => Get(nameof(Nav_NavigateNetwork));
        public static string Nav_NavigateStreaming  => Get(nameof(Nav_NavigateStreaming));
        public static string Nav_NavigatePrivacy    => Get(nameof(Nav_NavigatePrivacy));
        public static string Nav_NavigateTerminal   => Get(nameof(Nav_NavigateTerminal));

        // ─────────── BUTTONS ───────────
        public static string Button_Run                => Get(nameof(Button_Run));
        public static string Button_RunAll             => Get(nameof(Button_RunAll));
        public static string Button_Stop               => Get(nameof(Button_Stop));
        public static string Button_Cancel             => Get(nameof(Button_Cancel));
        public static string Button_Save               => Get(nameof(Button_Save));
        public static string Button_Close              => Get(nameof(Button_Close));
        public static string Button_Yes                => Get(nameof(Button_Yes));
        public static string Button_No                 => Get(nameof(Button_No));
        public static string Button_OK                 => Get(nameof(Button_OK));
        public static string Button_Settings           => Get(nameof(Button_Settings));
        public static string Button_About              => Get(nameof(Button_About));
        public static string Button_CreateRestorePoint => Get(nameof(Button_CreateRestorePoint));
        public static string Button_ExportLogs         => Get(nameof(Button_ExportLogs));
        public static string Button_ClearLogs          => Get(nameof(Button_ClearLogs));
        public static string Button_Cancel_OptTooltip  => Get(nameof(Button_Cancel_OptTooltip));

        // ─────────── STATUS ───────────
        public static string Status_Ready      => Get(nameof(Status_Ready));
        public static string Status_Running    => Get(nameof(Status_Running));
        public static string Status_Done       => Get(nameof(Status_Done));
        public static string Status_Error      => Get(nameof(Status_Error));
        public static string Status_Cancelled  => Get(nameof(Status_Cancelled));
        public static string Status_Cancelling => Get(nameof(Status_Cancelling));
        public static string Status_Simulated  => Get(nameof(Status_Simulated));
        public static string Status_CreatingRestorePoint => Get(nameof(Status_CreatingRestorePoint));
        public static string Status_RunningItem          => Get(nameof(Status_RunningItem));
        public static string Status_StopRequested        => Get(nameof(Status_StopRequested));

        // ─────────── SPLASH ───────────
        public static string Splash_CheckAdmin    => Get(nameof(Splash_CheckAdmin));
        public static string Splash_LoadModules   => Get(nameof(Splash_LoadModules));
        public static string Splash_LoadSettings  => Get(nameof(Splash_LoadSettings));
        public static string Splash_AnalyzeSystem => Get(nameof(Splash_AnalyzeSystem));
        public static string Splash_Ready         => Get(nameof(Splash_Ready));

        // ─────────── DIALOGS ───────────
        public static string Dialog_Confirm_Title         => Get(nameof(Dialog_Confirm_Title));
        public static string Dialog_RunOpt_Message        => Get(nameof(Dialog_RunOpt_Message));
        public static string Dialog_RunAll_Title          => Get(nameof(Dialog_RunAll_Title));
        public static string Dialog_RunAll_Message        => Get(nameof(Dialog_RunAll_Message));
        public static string Dialog_Critical_Title        => Get(nameof(Dialog_Critical_Title));
        public static string Dialog_Critical_Message      => Get(nameof(Dialog_Critical_Message));
        public static string Dialog_AdminRequired_Title   => Get(nameof(Dialog_AdminRequired_Title));
        public static string Dialog_AdminRequired_Message => Get(nameof(Dialog_AdminRequired_Message));
        public static string Dialog_Reboot_Title          => Get(nameof(Dialog_Reboot_Title));
        public static string Dialog_Reboot_Message        => Get(nameof(Dialog_Reboot_Message));
        public static string Dialog_Quarantine_Title      => Get(nameof(Dialog_Quarantine_Title));
        public static string Dialog_Quarantine_Message    => Get(nameof(Dialog_Quarantine_Message));

        // ─────────── SETTINGS ───────────
        public static string Settings_Title               => Get(nameof(Settings_Title));
        public static string Settings_ConfirmBeforeRun    => Get(nameof(Settings_ConfirmBeforeRun));
        public static string Settings_AutoRestorePoint    => Get(nameof(Settings_AutoRestorePoint));
        public static string Settings_RebootWarning       => Get(nameof(Settings_RebootWarning));
        public static string Settings_Simulation          => Get(nameof(Settings_Simulation));
        public static string Settings_ShowAdvanced        => Get(nameof(Settings_ShowAdvanced));
        public static string Settings_Benchmarks          => Get(nameof(Settings_Benchmarks));
        public static string Settings_AutoScrollTerminal  => Get(nameof(Settings_AutoScrollTerminal));
        public static string Settings_ShowAdminBadge      => Get(nameof(Settings_ShowAdminBadge));
        public static string Settings_LightTheme          => Get(nameof(Settings_LightTheme));
        public static string Settings_Language            => Get(nameof(Settings_Language));
        public static string Settings_Language_Auto       => Get(nameof(Settings_Language_Auto));
        public static string Settings_Language_FR         => Get(nameof(Settings_Language_FR));
        public static string Settings_Language_EN         => Get(nameof(Settings_Language_EN));
        public static string Settings_LanguageRestartHint => Get(nameof(Settings_LanguageRestartHint));
        public static string Settings_LanguageRestartNow  => Get(nameof(Settings_LanguageRestartNow));

        // ─────────── DASHBOARD ───────────
        public static string Dashboard_System       => Get(nameof(Dashboard_System));
        public static string Dashboard_CPU          => Get(nameof(Dashboard_CPU));
        public static string Dashboard_RAM          => Get(nameof(Dashboard_RAM));
        public static string Dashboard_Disk         => Get(nameof(Dashboard_Disk));
        public static string Dashboard_Uptime       => Get(nameof(Dashboard_Uptime));
        public static string Dashboard_OS           => Get(nameof(Dashboard_OS));
        public static string Dashboard_QuickActions => Get(nameof(Dashboard_QuickActions));

        // ─────────── COMMON MESSAGES ───────────
        public static string Msg_NoActiveAction  => Get(nameof(Msg_NoActiveAction));
        public static string Msg_TimeoutSeconds  => Get(nameof(Msg_TimeoutSeconds));
        public static string Msg_CancelledByUser => Get(nameof(Msg_CancelledByUser));
        public static string Msg_UacRefused      => Get(nameof(Msg_UacRefused));

        // ─────────── BADGES ───────────
        public static string Badge_Admin    => Get(nameof(Badge_Admin));
        public static string Badge_Reboot   => Get(nameof(Badge_Reboot));
        public static string Badge_Advanced => Get(nameof(Badge_Advanced));
        public static string Badge_Security => Get(nameof(Badge_Security));

        // ─────────── DASHBOARD ───────────
        public static string Dashboard_NavTitle       => Get(nameof(Dashboard_NavTitle));
        public static string Dashboard_CardCPU        => Get(nameof(Dashboard_CardCPU));
        public static string Dashboard_CardRAM        => Get(nameof(Dashboard_CardRAM));
        public static string Dashboard_CardDisk       => Get(nameof(Dashboard_CardDisk));
        public static string Dashboard_CardSession    => Get(nameof(Dashboard_CardSession));
        public static string Dashboard_CardSystem     => Get(nameof(Dashboard_CardSystem));
        public static string Dashboard_RecentActivity => Get(nameof(Dashboard_RecentActivity));
        public static string Dashboard_UptimePrefix   => Get(nameof(Dashboard_UptimePrefix));

        // ─────────── NAV BUTTONS (sidebar bottom) ───────────
        public static string Nav_Settings      => Get(nameof(Nav_Settings));
        public static string Nav_Legal         => Get(nameof(Nav_Legal));
        public static string Nav_About         => Get(nameof(Nav_About));
        public static string Nav_RestorePoint  => Get(nameof(Nav_RestorePoint));
        public static string Nav_ExportLogs    => Get(nameof(Nav_ExportLogs));

        // ─────────── v2.3.0 NAV TOOLS ───────────
        public static string Nav_Uninstaller  => Get(nameof(Nav_Uninstaller));
        public static string Nav_Updater      => Get(nameof(Nav_Updater));
        public static string Nav_DiskAnalyzer => Get(nameof(Nav_DiskAnalyzer));
        public static string Nav_Startup      => Get(nameof(Nav_Startup));
        public static string Nav_Browser      => Get(nameof(Nav_Browser));

        // ─────────── TERMINAL ───────────
        public static string Terminal_Live      => Get(nameof(Terminal_Live));
        public static string Terminal_Clear     => Get(nameof(Terminal_Clear));
        public static string Terminal_ExportTxt => Get(nameof(Terminal_ExportTxt));

        // ─────────── SETTINGS DESCRIPTIONS ───────────
        public static string Settings_ConfirmDesc       => Get(nameof(Settings_ConfirmDesc));
        public static string Settings_AutoRestoreDesc   => Get(nameof(Settings_AutoRestoreDesc));
        public static string Settings_RebootDesc        => Get(nameof(Settings_RebootDesc));
        public static string Settings_SimulationDesc    => Get(nameof(Settings_SimulationDesc));
        public static string Settings_AdvancedDesc      => Get(nameof(Settings_AdvancedDesc));
        public static string Settings_BenchmarksDesc    => Get(nameof(Settings_BenchmarksDesc));
        public static string Settings_AutoScrollDesc    => Get(nameof(Settings_AutoScrollDesc));
        public static string Settings_AdminBadgeDesc    => Get(nameof(Settings_AdminBadgeDesc));
        public static string Settings_LightThemeDesc    => Get(nameof(Settings_LightThemeDesc));
        public static string Settings_HeaderSecurity    => Get(nameof(Settings_HeaderSecurity));
        public static string Settings_HeaderInterface   => Get(nameof(Settings_HeaderInterface));
        public static string Settings_HeaderLanguage    => Get(nameof(Settings_HeaderLanguage));

        // ─────────── OPTIM NAMES ───────────
        public static string Optim_gaming_highperf_Name        => Get(nameof(Optim_gaming_highperf_Name));
        public static string Optim_gaming_gamedvr_Name         => Get(nameof(Optim_gaming_gamedvr_Name));
        public static string Optim_gaming_fullscreen_Name      => Get(nameof(Optim_gaming_fullscreen_Name));
        public static string Optim_gaming_priority_Name        => Get(nameof(Optim_gaming_priority_Name));
        public static string Optim_gaming_directx_Name         => Get(nameof(Optim_gaming_directx_Name));
        public static string Optim_gaming_kill_processes_Name  => Get(nameof(Optim_gaming_kill_processes_Name));
        public static string Optim_gaming_fps_unlock_Name      => Get(nameof(Optim_gaming_fps_unlock_Name));
        public static string Optim_gaming_gpu_schedule_Name    => Get(nameof(Optim_gaming_gpu_schedule_Name));

        public static string Optim_oldpc_startup_Name    => Get(nameof(Optim_oldpc_startup_Name));
        public static string Optim_oldpc_animations_Name => Get(nameof(Optim_oldpc_animations_Name));
        public static string Optim_oldpc_registry_Name   => Get(nameof(Optim_oldpc_registry_Name));
        public static string Optim_oldpc_ram_Name        => Get(nameof(Optim_oldpc_ram_Name));
        public static string Optim_oldpc_temp_Name       => Get(nameof(Optim_oldpc_temp_Name));
        public static string Optim_oldpc_defrag_Name     => Get(nameof(Optim_oldpc_defrag_Name));
        public static string Optim_oldpc_theme_Name      => Get(nameof(Optim_oldpc_theme_Name));

        public static string Optim_clean_disk_Name      => Get(nameof(Optim_clean_disk_Name));
        public static string Optim_clean_recycle_Name   => Get(nameof(Optim_clean_recycle_Name));
        public static string Optim_clean_logs_Name      => Get(nameof(Optim_clean_logs_Name));
        public static string Optim_clean_prefetch_Name  => Get(nameof(Optim_clean_prefetch_Name));
        public static string Optim_clean_bloatware_Name => Get(nameof(Optim_clean_bloatware_Name));
        public static string Optim_clean_repair_Name    => Get(nameof(Optim_clean_repair_Name));
        public static string Optim_clean_antivirus_Name => Get(nameof(Optim_clean_antivirus_Name));

        public static string Optim_net_tcpip_Name          => Get(nameof(Optim_net_tcpip_Name));
        public static string Optim_net_reset_Name          => Get(nameof(Optim_net_reset_Name));
        public static string Optim_net_dns_fast_Name       => Get(nameof(Optim_net_dns_fast_Name));
        public static string Optim_net_dns_restore_Name    => Get(nameof(Optim_net_dns_restore_Name));
        public static string Optim_net_ping_Name           => Get(nameof(Optim_net_ping_Name));
        public static string Optim_net_telemetry_block_Name => Get(nameof(Optim_net_telemetry_block_Name));
        public static string Optim_net_flush_dns_Name      => Get(nameof(Optim_net_flush_dns_Name));
        public static string Optim_net_reset_firewall_Name => Get(nameof(Optim_net_reset_firewall_Name));
        public static string Optim_net_speed_test_Name     => Get(nameof(Optim_net_speed_test_Name));
        public static string Optim_net_info_Name           => Get(nameof(Optim_net_info_Name));

        public static string Optim_stream_perf_mode_Name     => Get(nameof(Optim_stream_perf_mode_Name));
        public static string Optim_stream_cpu_prio_Name      => Get(nameof(Optim_stream_cpu_prio_Name));
        public static string Optim_stream_game_mode_off_Name => Get(nameof(Optim_stream_game_mode_off_Name));
        public static string Optim_stream_hags_off_Name      => Get(nameof(Optim_stream_hags_off_Name));
        public static string Optim_stream_killer_Name        => Get(nameof(Optim_stream_killer_Name));
        public static string Optim_stream_clean_cache_Name   => Get(nameof(Optim_stream_clean_cache_Name));

        // Confidentialité (v2.4.0)
        public static string Optim_priv_telemetry_Name           => Get(nameof(Optim_priv_telemetry_Name));
        public static string Optim_priv_advertising_id_Name      => Get(nameof(Optim_priv_advertising_id_Name));
        public static string Optim_priv_activity_history_Name    => Get(nameof(Optim_priv_activity_history_Name));
        public static string Optim_priv_location_Name            => Get(nameof(Optim_priv_location_Name));
        public static string Optim_priv_tailored_Name            => Get(nameof(Optim_priv_tailored_Name));
        public static string Optim_priv_app_launch_tracking_Name => Get(nameof(Optim_priv_app_launch_tracking_Name));
        public static string Optim_priv_feedback_Name            => Get(nameof(Optim_priv_feedback_Name));

        public static string Optim_priv_telemetry_Desc           => Get(nameof(Optim_priv_telemetry_Desc));
        public static string Optim_priv_advertising_id_Desc      => Get(nameof(Optim_priv_advertising_id_Desc));
        public static string Optim_priv_activity_history_Desc    => Get(nameof(Optim_priv_activity_history_Desc));
        public static string Optim_priv_location_Desc            => Get(nameof(Optim_priv_location_Desc));
        public static string Optim_priv_tailored_Desc            => Get(nameof(Optim_priv_tailored_Desc));
        public static string Optim_priv_app_launch_tracking_Desc => Get(nameof(Optim_priv_app_launch_tracking_Desc));
        public static string Optim_priv_feedback_Desc            => Get(nameof(Optim_priv_feedback_Desc));

        // ─────────── OPTIM DESCRIPTIONS ───────────
        public static string Optim_gaming_highperf_Desc        => Get(nameof(Optim_gaming_highperf_Desc));
        public static string Optim_gaming_gamedvr_Desc         => Get(nameof(Optim_gaming_gamedvr_Desc));
        public static string Optim_gaming_fullscreen_Desc      => Get(nameof(Optim_gaming_fullscreen_Desc));
        public static string Optim_gaming_priority_Desc        => Get(nameof(Optim_gaming_priority_Desc));
        public static string Optim_gaming_directx_Desc         => Get(nameof(Optim_gaming_directx_Desc));
        public static string Optim_gaming_kill_processes_Desc  => Get(nameof(Optim_gaming_kill_processes_Desc));
        public static string Optim_gaming_fps_unlock_Desc      => Get(nameof(Optim_gaming_fps_unlock_Desc));
        public static string Optim_gaming_gpu_schedule_Desc    => Get(nameof(Optim_gaming_gpu_schedule_Desc));

        public static string Optim_oldpc_startup_Desc    => Get(nameof(Optim_oldpc_startup_Desc));
        public static string Optim_oldpc_animations_Desc => Get(nameof(Optim_oldpc_animations_Desc));
        public static string Optim_oldpc_registry_Desc   => Get(nameof(Optim_oldpc_registry_Desc));
        public static string Optim_oldpc_ram_Desc        => Get(nameof(Optim_oldpc_ram_Desc));
        public static string Optim_oldpc_temp_Desc       => Get(nameof(Optim_oldpc_temp_Desc));
        public static string Optim_oldpc_defrag_Desc     => Get(nameof(Optim_oldpc_defrag_Desc));
        public static string Optim_oldpc_theme_Desc      => Get(nameof(Optim_oldpc_theme_Desc));

        public static string Optim_clean_disk_Desc      => Get(nameof(Optim_clean_disk_Desc));
        public static string Optim_clean_recycle_Desc   => Get(nameof(Optim_clean_recycle_Desc));
        public static string Optim_clean_logs_Desc      => Get(nameof(Optim_clean_logs_Desc));
        public static string Optim_clean_prefetch_Desc  => Get(nameof(Optim_clean_prefetch_Desc));
        public static string Optim_clean_bloatware_Desc => Get(nameof(Optim_clean_bloatware_Desc));
        public static string Optim_clean_repair_Desc    => Get(nameof(Optim_clean_repair_Desc));
        public static string Optim_clean_antivirus_Desc => Get(nameof(Optim_clean_antivirus_Desc));

        public static string Optim_net_tcpip_Desc           => Get(nameof(Optim_net_tcpip_Desc));
        public static string Optim_net_reset_Desc           => Get(nameof(Optim_net_reset_Desc));
        public static string Optim_net_dns_fast_Desc        => Get(nameof(Optim_net_dns_fast_Desc));
        public static string Optim_net_dns_restore_Desc     => Get(nameof(Optim_net_dns_restore_Desc));
        public static string Optim_net_ping_Desc            => Get(nameof(Optim_net_ping_Desc));
        public static string Optim_net_telemetry_block_Desc => Get(nameof(Optim_net_telemetry_block_Desc));
        public static string Optim_net_flush_dns_Desc       => Get(nameof(Optim_net_flush_dns_Desc));
        public static string Optim_net_reset_firewall_Desc  => Get(nameof(Optim_net_reset_firewall_Desc));
        public static string Optim_net_speed_test_Desc      => Get(nameof(Optim_net_speed_test_Desc));
        public static string Optim_net_info_Desc            => Get(nameof(Optim_net_info_Desc));

        public static string Optim_stream_perf_mode_Desc     => Get(nameof(Optim_stream_perf_mode_Desc));
        public static string Optim_stream_cpu_prio_Desc      => Get(nameof(Optim_stream_cpu_prio_Desc));
        public static string Optim_stream_game_mode_off_Desc => Get(nameof(Optim_stream_game_mode_off_Desc));
        public static string Optim_stream_hags_off_Desc      => Get(nameof(Optim_stream_hags_off_Desc));
        public static string Optim_stream_killer_Desc        => Get(nameof(Optim_stream_killer_Desc));
        public static string Optim_stream_clean_cache_Desc   => Get(nameof(Optim_stream_clean_cache_Desc));

        // ─────────── RESULT MESSAGES ───────────
        public static string Result_HighPerfActive       => Get(nameof(Result_HighPerfActive));
        public static string Result_FpsUnlocked          => Get(nameof(Result_FpsUnlocked));
        public static string Result_NoTargetProcesses    => Get(nameof(Result_NoTargetProcesses));
        public static string Result_KillCancelled        => Get(nameof(Result_KillCancelled));
        public static string Result_KillDialogTitle      => Get(nameof(Result_KillDialogTitle));
        public static string Result_KillDialogMessage    => Get(nameof(Result_KillDialogMessage));
        public static string Result_ProcessesKilled      => Get(nameof(Result_ProcessesKilled));
        public static string Result_ProcessesNotKilled   => Get(nameof(Result_ProcessesNotKilled));
        public static string Result_NoProcessKilled      => Get(nameof(Result_NoProcessKilled));
        public static string Result_QuarantineRefused    => Get(nameof(Result_QuarantineRefused));
        public static string Result_QuarantineSuccess    => Get(nameof(Result_QuarantineSuccess));
        public static string Result_QuarantinePartial    => Get(nameof(Result_QuarantinePartial));
        public static string Result_QuarantineTimeout    => Get(nameof(Result_QuarantineTimeout));
        public static string Result_QuarantineLaunched   => Get(nameof(Result_QuarantineLaunched));
        public static string Result_ScanNoThreats        => Get(nameof(Result_ScanNoThreats));
        public static string Result_DefenderUnavailable  => Get(nameof(Result_DefenderUnavailable));
        public static string Result_ScanTimeout          => Get(nameof(Result_ScanTimeout));
        public static string Result_ScanCancelled        => Get(nameof(Result_ScanCancelled));
        public static string Result_ScanError            => Get(nameof(Result_ScanError));
        public static string Result_StreamerModeOn       => Get(nameof(Result_StreamerModeOn));
        public static string Result_NoEncoderDetected    => Get(nameof(Result_NoEncoderDetected));
        public static string Result_EncoderBoosted       => Get(nameof(Result_EncoderBoosted));
        public static string Result_GameModeOff          => Get(nameof(Result_GameModeOff));
        public static string Result_HagsOff              => Get(nameof(Result_HagsOff));
        public static string Result_NoParasites          => Get(nameof(Result_NoParasites));
        public static string Result_ParasitesKilled      => Get(nameof(Result_ParasitesKilled));
        public static string Result_NoObsCache           => Get(nameof(Result_NoObsCache));
        public static string Result_ObsCacheCleared      => Get(nameof(Result_ObsCacheCleared));
        public static string Result_TcpOptimized         => Get(nameof(Result_TcpOptimized));
        public static string Result_PingOptimized        => Get(nameof(Result_PingOptimized));
        public static string Result_TelemetryBlocked     => Get(nameof(Result_TelemetryBlocked));
        public static string Result_NetReset             => Get(nameof(Result_NetReset));
        public static string Result_FirewallReset        => Get(nameof(Result_FirewallReset));
        public static string Result_NoActiveAdapter      => Get(nameof(Result_NoActiveAdapter));
        public static string Result_DnsDomainJoined      => Get(nameof(Result_DnsDomainJoined));
        public static string Result_DnsDomainCheckFailed => Get(nameof(Result_DnsDomainCheckFailed));
        public static string Result_DnsBackupFailed      => Get(nameof(Result_DnsBackupFailed));
        public static string Result_DnsNoBackup          => Get(nameof(Result_DnsNoBackup));
        public static string Result_DnsRestoreIncomplete => Get(nameof(Result_DnsRestoreIncomplete));

        // ─────────── ABOUT ───────────
        public static string About_Title             => Get(nameof(About_Title));
        public static string About_Subtitle          => Get(nameof(About_Subtitle));
        public static string About_Version           => Get(nameof(About_Version));
        public static string About_Developer         => Get(nameof(About_Developer));
        public static string About_Compatibility     => Get(nameof(About_Compatibility));
        public static string About_Framework         => Get(nameof(About_Framework));
        public static string About_DiagnosticHeader  => Get(nameof(About_DiagnosticHeader));
        public static string About_CopySystemInfo    => Get(nameof(About_CopySystemInfo));
        public static string About_ExportReport      => Get(nameof(About_ExportReport));

        // ─────────── LEGAL ───────────
        public static string Legal_Title              => Get(nameof(Legal_Title));
        public static string Legal_PrivacyHeader      => Get(nameof(Legal_PrivacyHeader));
        public static string Legal_PrivacyContent     => Get(nameof(Legal_PrivacyContent));
        public static string Legal_RestoreHeader      => Get(nameof(Legal_RestoreHeader));
        public static string Legal_RestoreContent     => Get(nameof(Legal_RestoreContent));
        public static string Legal_DisclaimerHeader   => Get(nameof(Legal_DisclaimerHeader));
        public static string Legal_DisclaimerContent  => Get(nameof(Legal_DisclaimerContent));
        public static string Legal_AuditHeader        => Get(nameof(Legal_AuditHeader));
        public static string Legal_AuditContent       => Get(nameof(Legal_AuditContent));
        public static string Legal_Footer             => Get(nameof(Legal_Footer));

        // ─────────── LOG MESSAGES ───────────
        public static string Log_AppStarted     => Get(nameof(Log_AppStarted));
        public static string Log_PrivacyNotice  => Get(nameof(Log_PrivacyNotice));
        public static string Log_AdminWarning   => Get(nameof(Log_AdminWarning));
        public static string Log_AdminConfirmed => Get(nameof(Log_AdminConfirmed));
        public static string Log_SensorsInitialized => Get(nameof(Log_SensorsInitialized));
        public static string Log_UpdateFound        => Get(nameof(Log_UpdateFound));
        public static string Log_SpaceFreed         => Get(nameof(Log_SpaceFreed));

        // ─────────── LOG CATEGORIES ───────────
        public static string Category_System    => Get(nameof(Category_System));
        public static string Category_Privacy   => Get(nameof(Category_Privacy));
        public static string Category_App       => Get(nameof(Category_App));
        public static string Category_Cleaning  => Get(nameof(Category_Cleaning));
        public static string Category_Network   => Get(nameof(Category_Network));
        public static string Category_Gaming    => Get(nameof(Category_Gaming));
        public static string Category_OldPC     => Get(nameof(Category_OldPC));
        public static string Category_Streaming => Get(nameof(Category_Streaming));
        public static string Category_Benchmark => Get(nameof(Category_Benchmark));
        public static string Category_Settings  => Get(nameof(Category_Settings));

        // ─────────── DASHBOARD INLINE ───────────
        public static string Dashboard_OptimizationsRunSuffix => Get(nameof(Dashboard_OptimizationsRunSuffix));
        public static string Dashboard_DiskUnitGo             => Get(nameof(Dashboard_DiskUnitGo));

        // ─────────── v2.3.0 UNINSTALLER ───────────
        public static string Uninstaller_Title             => Get(nameof(Uninstaller_Title));
        public static string Uninstaller_SearchPlaceholder => Get(nameof(Uninstaller_SearchPlaceholder));
        public static string Uninstaller_Count             => Get(nameof(Uninstaller_Count));
        public static string Uninstaller_Loading           => Get(nameof(Uninstaller_Loading));
        public static string Uninstaller_Refresh           => Get(nameof(Uninstaller_Refresh));
        public static string Uninstaller_UninstallSelected => Get(nameof(Uninstaller_UninstallSelected));
        public static string Uninstaller_NoSelection       => Get(nameof(Uninstaller_NoSelection));
        public static string Uninstaller_ConfirmUninstall  => Get(nameof(Uninstaller_ConfirmUninstall));
        public static string Uninstaller_Uninstalling      => Get(nameof(Uninstaller_Uninstalling));
        public static string Uninstaller_LeftoversTitle    => Get(nameof(Uninstaller_LeftoversTitle));
        public static string Uninstaller_LeftoversFound    => Get(nameof(Uninstaller_LeftoversFound));
        public static string Uninstaller_LeftoversRemoved  => Get(nameof(Uninstaller_LeftoversRemoved));

        // ─────────── v2.3.0 SOFTWARE UPDATER ───────────
        public static string Updater_Title          => Get(nameof(Updater_Title));
        public static string Updater_Loading        => Get(nameof(Updater_Loading));
        public static string Updater_WingetMissing  => Get(nameof(Updater_WingetMissing));
        public static string Updater_AllUpToDate    => Get(nameof(Updater_AllUpToDate));
        public static string Updater_Count          => Get(nameof(Updater_Count));
        public static string Updater_UpdateSelected => Get(nameof(Updater_UpdateSelected));
        public static string Updater_NoSelection    => Get(nameof(Updater_NoSelection));
        public static string Updater_Updating       => Get(nameof(Updater_Updating));
        public static string Updater_Done           => Get(nameof(Updater_Done));
        public static string Updater_WindowsUpdate     => Get(nameof(Updater_WindowsUpdate));
        public static string Updater_WindowsUpdateHint => Get(nameof(Updater_WindowsUpdateHint));

        // ─────────── v2.3.0 DISK ANALYZER ───────────
        public static string DiskAnalyzer_Title    => Get(nameof(DiskAnalyzer_Title));
        public static string DiskAnalyzer_Up       => Get(nameof(DiskAnalyzer_Up));
        public static string DiskAnalyzer_Scanning => Get(nameof(DiskAnalyzer_Scanning));
        public static string DiskAnalyzer_Status   => Get(nameof(DiskAnalyzer_Status));
        public static string DiskAnalyzer_Start    => Get(nameof(DiskAnalyzer_Start));
        public static string DiskAnalyzer_Stop     => Get(nameof(DiskAnalyzer_Stop));
        public static string DiskAnalyzer_Idle     => Get(nameof(DiskAnalyzer_Idle));
        public static string DiskAnalyzer_Stopped  => Get(nameof(DiskAnalyzer_Stopped));

        // ─────────── v2.3.0 STARTUP MANAGER ───────────
        public static string Startup_Title        => Get(nameof(Startup_Title));
        public static string Startup_Loading      => Get(nameof(Startup_Loading));
        public static string Startup_Status       => Get(nameof(Startup_Status));
        public static string Startup_ToggleFailed => Get(nameof(Startup_ToggleFailed));
        public static string Startup_Enabled      => Get(nameof(Startup_Enabled));
        public static string Startup_Disabled     => Get(nameof(Startup_Disabled));
        public static string Startup_AddTask      => Get(nameof(Startup_AddTask));
        public static string Startup_AddFailed    => Get(nameof(Startup_AddFailed));

        // ─────────── v2.3.0 BROWSER CLEANER ───────────
        public static string Browser_Title      => Get(nameof(Browser_Title));
        public static string Browser_Warning    => Get(nameof(Browser_Warning));
        public static string Browser_Cache      => Get(nameof(Browser_Cache));
        public static string Browser_Cookies    => Get(nameof(Browser_Cookies));
        public static string Browser_History    => Get(nameof(Browser_History));
        public static string Browser_NoBrowser  => Get(nameof(Browser_NoBrowser));
        public static string Browser_Detected   => Get(nameof(Browser_Detected));
        public static string Browser_CleanNow   => Get(nameof(Browser_CleanNow));
        public static string Browser_Confirm    => Get(nameof(Browser_Confirm));
        public static string Browser_Cleaning   => Get(nameof(Browser_Cleaning));
        public static string Browser_Done       => Get(nameof(Browser_Done));

        // ─────────── v2.4.0 SERVICES MANAGER ───────────
        public static string Nav_Services             => Get(nameof(Nav_Services));
        public static string Services_Title           => Get(nameof(Services_Title));
        public static string Services_Subtitle        => Get(nameof(Services_Subtitle));
        public static string Services_Loading         => Get(nameof(Services_Loading));
        public static string Services_Status          => Get(nameof(Services_Status));
        public static string Services_Applying        => Get(nameof(Services_Applying));
        public static string Services_AdminRequired   => Get(nameof(Services_AdminRequired));
        public static string Services_ToggleFailed    => Get(nameof(Services_ToggleFailed));
        public static string Service_DiagTrack_Desc        => Get(nameof(Service_DiagTrack_Desc));
        public static string Service_dmwappushservice_Desc => Get(nameof(Service_dmwappushservice_Desc));
        public static string Service_Fax_Desc              => Get(nameof(Service_Fax_Desc));
        public static string Service_RetailDemo_Desc       => Get(nameof(Service_RetailDemo_Desc));
        public static string Service_RemoteRegistry_Desc   => Get(nameof(Service_RemoteRegistry_Desc));
        public static string Service_MapsBroker_Desc       => Get(nameof(Service_MapsBroker_Desc));
        public static string Service_WMPNetworkSvc_Desc    => Get(nameof(Service_WMPNetworkSvc_Desc));
        public static string Service_WerSvc_Desc           => Get(nameof(Service_WerSvc_Desc));
        public static string Service_lfsvc_Desc            => Get(nameof(Service_lfsvc_Desc));

        // ─────────── v2.4.0 RESTORE POINT MANAGER ───────────
        public static string Nav_Restore             => Get(nameof(Nav_Restore));
        public static string Restore_Title           => Get(nameof(Restore_Title));
        public static string Restore_Create          => Get(nameof(Restore_Create));
        public static string Restore_Open            => Get(nameof(Restore_Open));
        public static string Restore_DeleteAll       => Get(nameof(Restore_DeleteAll));
        public static string Restore_Empty           => Get(nameof(Restore_Empty));
        public static string Restore_Status          => Get(nameof(Restore_Status));
        public static string Restore_Loading         => Get(nameof(Restore_Loading));
        public static string Restore_Creating        => Get(nameof(Restore_Creating));
        public static string Restore_Created         => Get(nameof(Restore_Created));
        public static string Restore_CreateFailed    => Get(nameof(Restore_CreateFailed));
        public static string Restore_Deleting        => Get(nameof(Restore_Deleting));
        public static string Restore_Deleted         => Get(nameof(Restore_Deleted));
        public static string Restore_DeleteFailed    => Get(nameof(Restore_DeleteFailed));
        public static string Restore_DeleteConfirm   => Get(nameof(Restore_DeleteConfirm));
        public static string Restore_AdminRequired   => Get(nameof(Restore_AdminRequired));
        public static string Restore_ManualPointName => Get(nameof(Restore_ManualPointName));
        public static string Restore_OpenFailed      => Get(nameof(Restore_OpenFailed));

        // ─────────── v2.5.0 PROFILS 1-CLIC ───────────
        public static string Nav_Profiles         => Get(nameof(Nav_Profiles));
        public static string Profiles_Title       => Get(nameof(Profiles_Title));
        public static string Profiles_Subtitle    => Get(nameof(Profiles_Subtitle));
        public static string Profiles_Apply       => Get(nameof(Profiles_Apply));
        public static string Profiles_OptimsLabel => Get(nameof(Profiles_OptimsLabel));
        public static string Preset_Gaming_Name    => Get(nameof(Preset_Gaming_Name));
        public static string Preset_Gaming_Desc    => Get(nameof(Preset_Gaming_Desc));
        public static string Preset_Perf_Name      => Get(nameof(Preset_Perf_Name));
        public static string Preset_Perf_Desc      => Get(nameof(Preset_Perf_Desc));
        public static string Preset_Privacy_Name   => Get(nameof(Preset_Privacy_Name));
        public static string Preset_Privacy_Desc   => Get(nameof(Preset_Privacy_Desc));
        public static string Preset_Balanced_Name  => Get(nameof(Preset_Balanced_Name));
        public static string Preset_Balanced_Desc  => Get(nameof(Preset_Balanced_Desc));
        public static string Dialog_RunPreset_Title   => Get(nameof(Dialog_RunPreset_Title));
        public static string Dialog_RunPreset_Message => Get(nameof(Dialog_RunPreset_Message));

        // ─────────── v2.5.0 DÉBLOAT UWP ───────────
        public static string Nav_Appx                => Get(nameof(Nav_Appx));
        public static string Appx_Title              => Get(nameof(Appx_Title));
        public static string Appx_Subtitle           => Get(nameof(Appx_Subtitle));
        public static string Appx_Loading            => Get(nameof(Appx_Loading));
        public static string Appx_Uninstalling       => Get(nameof(Appx_Uninstalling));
        public static string Appx_Status             => Get(nameof(Appx_Status));
        public static string Appx_UninstallSelected  => Get(nameof(Appx_UninstallSelected));
        public static string Appx_ConfirmUninstall   => Get(nameof(Appx_ConfirmUninstall));
        public static string Appx_Done               => Get(nameof(Appx_Done));
        public static string Appx_NoneSelected       => Get(nameof(Appx_NoneSelected));

        // ─────────── v2.5.0 GROS FICHIERS & DOUBLONS ───────────
        public static string Nav_Files            => Get(nameof(Nav_Files));
        public static string Files_Title          => Get(nameof(Files_Title));
        public static string Files_ChooseFolder   => Get(nameof(Files_ChooseFolder));
        public static string Files_NoFolder       => Get(nameof(Files_NoFolder));
        public static string Files_ModeLarge      => Get(nameof(Files_ModeLarge));
        public static string Files_ModeDuplicates => Get(nameof(Files_ModeDuplicates));
        public static string Files_Start          => Get(nameof(Files_Start));
        public static string Files_Stop           => Get(nameof(Files_Stop));
        public static string Files_Scanning       => Get(nameof(Files_Scanning));
        public static string Files_Status         => Get(nameof(Files_Status));
        public static string Files_Empty          => Get(nameof(Files_Empty));
        public static string Files_DeleteSelected => Get(nameof(Files_DeleteSelected));
        public static string Files_ConfirmDelete  => Get(nameof(Files_ConfirmDelete));
        public static string Files_Done           => Get(nameof(Files_Done));
        public static string Files_NoneSelected   => Get(nameof(Files_NoneSelected));
        public static string Files_GroupLabel     => Get(nameof(Files_GroupLabel));

        // ─────────── v2.5.0 RAPPORT DE SANTÉ ───────────
        public static string Nav_Health              => Get(nameof(Nav_Health));
        public static string Health_Title            => Get(nameof(Health_Title));
        public static string Health_Subtitle         => Get(nameof(Health_Subtitle));
        public static string Health_Loading          => Get(nameof(Health_Loading));
        public static string Health_Refresh          => Get(nameof(Health_Refresh));
        public static string Health_Fix              => Get(nameof(Health_Fix));
        public static string Health_Ram_Title        => Get(nameof(Health_Ram_Title));
        public static string Health_Ram_Detail       => Get(nameof(Health_Ram_Detail));
        public static string Health_Disk_Title       => Get(nameof(Health_Disk_Title));
        public static string Health_Disk_Detail      => Get(nameof(Health_Disk_Detail));
        public static string Health_Temp_Title       => Get(nameof(Health_Temp_Title));
        public static string Health_Temp_Detail      => Get(nameof(Health_Temp_Detail));
        public static string Health_Telemetry_Title  => Get(nameof(Health_Telemetry_Title));
        public static string Health_Telemetry_On     => Get(nameof(Health_Telemetry_On));
        public static string Health_Telemetry_Off    => Get(nameof(Health_Telemetry_Off));
        public static string Health_Startup_Title    => Get(nameof(Health_Startup_Title));
        public static string Health_Startup_Detail   => Get(nameof(Health_Startup_Detail));
        public static string Health_Restore_Title    => Get(nameof(Health_Restore_Title));
        public static string Health_Restore_None     => Get(nameof(Health_Restore_None));
        public static string Health_Restore_Ok       => Get(nameof(Health_Restore_Ok));
        public static string Health_Restore_Unknown  => Get(nameof(Health_Restore_Unknown));

        // ─────────── v2.3.0 UPDATE CHECK ───────────
        public static string Update_Available        => Get(nameof(Update_Available));
        public static string Settings_UpdateCheck    => Get(nameof(Settings_UpdateCheck));
        public static string Settings_UpdateCheckDesc => Get(nameof(Settings_UpdateCheckDesc));

        // ─────────── v2.4.0 TRAY / DÉMARRAGE ───────────
        public static string Settings_MinimizeTray      => Get(nameof(Settings_MinimizeTray));
        public static string Settings_MinimizeTrayDesc  => Get(nameof(Settings_MinimizeTrayDesc));
        public static string Settings_LaunchStartup     => Get(nameof(Settings_LaunchStartup));
        public static string Settings_LaunchStartupDesc => Get(nameof(Settings_LaunchStartupDesc));
        public static string Tray_Open           => Get(nameof(Tray_Open));
        public static string Tray_QuickClean     => Get(nameof(Tray_QuickClean));
        public static string Tray_Quit           => Get(nameof(Tray_Quit));
        public static string Tray_MinimizedHint  => Get(nameof(Tray_MinimizedHint));
        public static string Tray_Cleaning       => Get(nameof(Tray_Cleaning));
        public static string Tray_CleanDone      => Get(nameof(Tray_CleanDone));

        // ─────────── v2.3.0 HARDWARE SENSORS ───────────
        public static string Settings_HwSensors     => Get(nameof(Settings_HwSensors));
        public static string Settings_HwSensorsDesc => Get(nameof(Settings_HwSensorsDesc));

        // ─────────── v2.3.0 SCHEDULED SCANS ───────────
        public static string Settings_HeaderSchedule  => Get(nameof(Settings_HeaderSchedule));
        public static string Settings_ScheduleEnable  => Get(nameof(Settings_ScheduleEnable));
        public static string Settings_ScheduleDesc    => Get(nameof(Settings_ScheduleDesc));
        public static string Settings_ScheduleDaily   => Get(nameof(Settings_ScheduleDaily));
        public static string Settings_ScheduleWeekly  => Get(nameof(Settings_ScheduleWeekly));
        public static string Settings_ScheduleMonthly => Get(nameof(Settings_ScheduleMonthly));
        public static string Settings_ScheduleFailed  => Get(nameof(Settings_ScheduleFailed));

        // ─────────── WINDOW CONTROLS TOOLTIPS ───────────
        public static string Tooltip_Minimize => Get(nameof(Tooltip_Minimize));
        public static string Tooltip_Maximize => Get(nameof(Tooltip_Maximize));
        public static string Tooltip_Close    => Get(nameof(Tooltip_Close));

        // ─────────── v2.3.0 DASHBOARD ───────────
        public static string Dashboard_PerfScoreTitle => Get(nameof(Dashboard_PerfScoreTitle));
        public static string Dashboard_PerfScoreHint  => Get(nameof(Dashboard_PerfScoreHint));
        public static string Module_OptimizationsAvailable => Get(nameof(Module_OptimizationsAvailable));
        public static string Score_Excellent => Get(nameof(Score_Excellent));
        public static string Score_Good      => Get(nameof(Score_Good));
        public static string Score_Average   => Get(nameof(Score_Average));
        public static string Score_Low       => Get(nameof(Score_Low));
        public static string Score_Critical  => Get(nameof(Score_Critical));
        public static string Dashboard_CardGPU        => Get(nameof(Dashboard_CardGPU));
        public static string Dashboard_GpuLoad        => Get(nameof(Dashboard_GpuLoad));
        public static string Dashboard_GpuTemp        => Get(nameof(Dashboard_GpuTemp));
    }
}
